# Generated by Django 5.2 on 2025-08-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenders',
            name='slug',
        ),
        migrations.AddField(
            model_name='tenderstranslation',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True, verbose_name='Slug'),
        ),
    ]
