# Generated by Django 5.2 on 2025-04-17 05:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='text',
            field=ckeditor.fields.RichTextField(default=2, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
