# Generated by Django 5.2 on 2025-05-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_feedbackstranslation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='image',
            field=models.ImageField(default=1, upload_to='feedbacks', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
