# Generated by Django 5.2 on 2025-04-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slogan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=100, verbose_name='Первый Заголовок')),
                ('second_title', models.CharField(max_length=100, verbose_name='Первый Заголовок')),
                ('third_title', models.CharField(max_length=100, verbose_name='Первый Заголовок')),
            ],
            options={
                'verbose_name': 'Слоган',
                'verbose_name_plural': 'Слоганы',
            },
        ),
    ]
