# Generated by Django 5.2 on 2025-05-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_feedbacks_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='image',
            field=models.ImageField(upload_to='feedbacks/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.ImageField(blank=True, upload_to='partners/', verbose_name='Изображение'),
        ),
    ]
