# Generated by Django 5.2 on 2025-10-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_feedbacks_image_alter_partners_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=350, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='partners/', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ['-created_at'],
            },
        ),
    ]
