# Generated by Django 5.2 on 2025-04-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
