# Generated by Django 5.2 on 2025-11-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mediapartners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediapartners',
            options={'ordering': ['-created_at'], 'verbose_name': 'Медиа Партнёр', 'verbose_name_plural': 'Медиа Партнёры'},
        ),
    ]
