# Generated by Django 5.2 on 2025-04-14 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_news_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
