# Generated by Django 5.2 on 2025-04-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_slider_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
    ]
