# Generated by Django 5.2 on 2025-04-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='title',
            field=models.CharField(blank=True, max_length=350, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='author',
            field=models.CharField(max_length=200, verbose_name='Автор'),
        ),
    ]
