# Generated by Django 5.2 on 2025-04-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
