# Generated by Django 5.2 on 2025-04-17 05:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
    ]
