# Generated by Django 5.2 on 2025-04-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Инфо', 'verbose_name_plural': 'Инфо'},
        ),
    ]
