# Generated by Django 5.2 on 2025-04-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_info_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='poster',
            field=models.ImageField(default=1, upload_to='poster/'),
            preserve_default=False,
        ),
    ]
