# Generated by Django 5.2 on 2025-04-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_info_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='poster',
            field=models.ImageField(upload_to='poster/', verbose_name='Превью видео'),
        ),
    ]
