# Generated by Django 5.2 on 2025-05-01 08:19

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_info_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='news_images/', verbose_name='Фото'),
        ),
    ]
