# Generated by Django 5.2 on 2025-05-01 08:20

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='slider/', verbose_name='Фото'),
        ),
    ]
