# Generated by Django 5.2 on 2025-05-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_news_image_alter_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='file',
            field=models.FileField(upload_to='videosMain/', verbose_name='Видеоролик'),
        ),
    ]
