# Generated by Django 5.2 on 2025-05-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
