# Generated by Django 5.2 on 2025-11-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_statistic_projecttranslation_descr_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='project-videos/', verbose_name='видео если присутствует'),
        ),
    ]
